### ISSUE TITLE
Visualizador de Estado de Cuentas

### ISSUE THREAD

**Issue by jesus271088** [Ulises-Dominguez/visualizador-de-informacion-participante#10]
*Crear servicio de petición de estados de cuenta
*Crear modelo para visualización en tablas
*Crear tabla de FUED
*Crear tabla de FUF FUL
*Crear tabla de Anexo
*Análisis de Diseño y explotación de datos de acuerdo Mockup 

[2019-09-17_105822 mockup modulo ECD.pdf](https://github.com/Ulises-Dominguez/visualizador-de-informacion-participante/files/3623315/2019-09-17_105822.mockup.modulo.ECD.pdf)

**Comment by jesus271088** [comment]
![image](https://user-images.githubusercontent.com/2181094/65730177-813cdd80-e086-11e9-9e67-6d9701a9fbb3.png)

**Comment by jesus271088** [comment]
![image](https://user-images.githubusercontent.com/2181094/65730196-9285ea00-e086-11e9-9256-93f47aefca2e.png)

**Comment by jesus271088** [comment]
![image](https://user-images.githubusercontent.com/2181094/65730218-a2053300-e086-11e9-93bd-29cdf176bdca.png)

**Comment by Ulises-Dominguez** [comment]
Oye @jesus271088 podemos modificar el nombre del archivo del ECD cuando lo descargas? Justo ahora el nombre del archivo es [Clave del Participante].pdf por ejemplo. Me gustaría que viniera con el nombre de archivo que viene en los headers de la respuesta http, en el header Content-Disposition:

![image](https://user-images.githubusercontent.com/33697559/66233437-fc1e7d80-e6b0-11e9-9539-20a374abde23.png)

**Comment by jesus271088** [comment]
Listo ya fue cambiado el nombre de la descarga

**Comment by Ulises-Dominguez** [comment]
Oye @jesus271088  encontré hoy con un bug que deja al sistema en esta pantalla cuando el token ya expiró
![image](https://user-images.githubusercontent.com/33697559/67304787-fcdd4f00-f4b9-11e9-96af-c6a630ec7e68.png)
Yo creo que se debe a que la rutina que hace la pregunta de ECDs hasta encontrar el primero disponible lo está causando ya que el token ha expirado y por tanto todas las solicitudes fallan

**Comment by jesus271088** [comment]
Es por la autorización del token en fallo no sale el spinner, ya fue corregido ese  tema y se agrego un mensaje claro del error
![image](https://user-images.githubusercontent.com/2181094/67409887-d3d3c180-f580-11e9-9caf-8e690b65729c.png)
