### ISSUE TITLE
Dashboard Layout EDC

### ISSUE THREAD

**Issue by jesus271088** [Ulises-Dominguez/visualizador-de-informacion-participante#11]
Propuesta de diseño en base al Mockup de la visualización de indicadores y el visualizador de EDC

**Comment by jesus271088** [comment]
![image](https://user-images.githubusercontent.com/2181094/65341732-9f8e6f00-db96-11e9-9a6b-94f7e3958d5d.png)

**Comment by jesus271088** [comment]
![image](https://user-images.githubusercontent.com/2181094/65344366-1f1f3c80-db9d-11e9-937d-beca5ab1c614.png)

**Comment by jesus271088** [comment]
http://webservices.operati.com.mx:18008/#/login

**Comment by Ulises-Dominguez** [comment]
Más adelante revisaremos con mayor detalle la manera de representar la información, así como las estructuras de los _submódulos_ para estar más acorde a la planeación del producto final.
Buen trabajo!
