### ISSUE TITLE
Gráficas de energía

### ISSUE THREAD

**Issue by jesus271088** [Ulises-Dominguez/visualizador-de-informacion-participante#20]
Crear las siguientes gráficas
*Energía total consumida
*Compra de energía
*Energía por carga
*Contribución de energía de carga por día

**Comment by Ulises-Dominguez** [comment]
![image](https://user-images.githubusercontent.com/33697559/66223820-07b27a00-e69a-11e9-950a-90fd7e990df7.png)

Subclasificación de los activos

**Comment by Ulises-Dominguez** [comment]
![image](https://user-images.githubusercontent.com/33697559/66223844-17ca5980-e69a-11e9-9e85-b2db151ae6ee.png)

Mockup de las gráficas de energía (número 1 en el mockup). Las gráficas de la derecha están pendientes de determinar qué cálculo vamos a realizar para obtener sus datos.
